[package]
name = "syt-communication"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
syt-models = { path = "../syt-models" }
anyhow = { workspace = true }