[package]
name = "syt-web"
version = "0.1.0"
authors = ["Bruno-Camargo-V3ktor <v3ktoryt@gmail.com>"]
edition = "2021"

[dependencies]
dioxus = { version = "0.6.0", features = [] }

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
